### ISSUE TITLE
Environment issue

### ISSUE THREAD

**Issue by bbbts** [chenller/mmseg-extension#1]
Could you please upload a concise requirement.txt environment file? Thanks in advance!

**Comment by chenller** [comment]
I will provide a detailed installation procedure. It will take some time.

**Comment by bbbts** [comment]
> I will provide a detailed installation procedure. It will take some time.

Thank you for the help in advance!

**Comment by chenller** [comment]
The 'requirement.txt' file has been added. 
However, it is not recommended to install directly using this file. Please refer to tutorial [get_started.md](https://github.com/chenller/mmseg-extension/blob/main/docs/readme/get_started.md) for installation
