### ISSUE TITLE
numpy issue - error while training

### ISSUE THREAD

**Issue by bbbts** [chenller/mmseg-extension#3]
Here are the exact steps I followed while setting up the environment from scratch - 
<img width="663" alt="image" src="https://github.com/user-attachments/assets/afaee8dd-de7a-4646-8c49-473df1459523">

After this, I tried to run the following command to start the training - 
<img width="641" alt="image" src="https://github.com/user-attachments/assets/297a67e2-2e84-42e5-8edc-54456a7b4713">

For reference, my "upernet_internimage_b_512_160k_ade20k.py" file looks like this - 
<img width="799" alt="image" src="https://github.com/user-attachments/assets/225037bb-ca5d-45f9-a51e-4be9b923aa77">
<img width="641" alt="image" src="https://github.com/user-attachments/assets/01ed21c8-cd52-4ae6-9153-a698c129cef8">
<img width="599" alt="image" src="https://github.com/user-attachments/assets/43e2e620-0e9d-4e64-9adc-2800f52e3013">

After running the above training command, I am getting the following error - 
"ImportError: numpy.core.multiarray failed to import"
as seen here - 
<img width="922" alt="image" src="https://github.com/user-attachments/assets/b41e678b-9782-4d2c-8b8c-854dceecf214">

Please let me know what should be done. Thanks in advance!!

**Comment by chenller** [comment]
I don't think this is a bug caused by mmseg-ext, more like a bug caused by cv2. I did not encounter this error so I cannot give an accurate solution.
In my experience, you can try the following solutions: 
Option 1: Try opencv-python==4.10.0 and numpy==1.26.4 (This bug does not appear in my environment).
Option 2: Reduce the opencv-python version, you can try several lower versions.

**Comment by bbbts** [comment]
> I don't think this is a bug caused by mmseg-ext, more like a bug caused by cv2. I did not encounter this error so I cannot give an accurate solution. In my experience, you can try the following solutions: Option 1: Try opencv-python==4.10.0 and numpy==1.26.4 (This bug does not appear in my environment). Option 2: Reduce the opencv-python version, you can try several lower versions.

Thank you for the quick reply. I installed opencv-python==4.9.0.80 and numpy==1.26.3.
I am getting a different error now - 
![image](https://github.com/user-attachments/assets/6d25d272-90be-427e-a68a-403f76cb71bf)


Could you kindly export the whole environment you used so that I can use the same environment for this as well? (just for your reference, I am trying to use this project for semantic segmentation)

**Comment by chenller** [comment]
- Change the config referenced by the "mmsegext" line(line 2) in the _base_ variable in the config.py file to the absolute path. I will fix this bug in the next version
- Look at line 24 to the end of the requirements.txt file. Generated by the 'pip freeze' command

**Comment by chenller** [comment]
Also, add the code "import mmsegext" at the beginning of the file "tool/train.py"

**Comment by bbbts** [comment]
> import mmsegext

Thank you very much for the help.
So, the requirements.txt file looks like this - 
<img width="497" alt="image" src="https://github.com/user-attachments/assets/26614ad6-b72f-4b72-b2e5-145671baedf5">

Should I uncomment the line 24? (pip freeze) or should I uncomment every line that is commented out after line 24?

Also, should I mention the absolute path (in my case "/home/bhattb3/MMSEG/configs/__base__" as you can see from the picture below) in the config.py file (in line 37 where it says "BASE_KEY")?
<img width="281" alt="image" src="https://github.com/user-attachments/assets/96bd5750-b524-49f6-8bc3-87db57372eee">

**Comment by chenller** [comment]
1. Cancelling the comment is not necessary, I just want to let you know the environment I am using. You can do nothing about the file `requirements.txt`.
2. `mmengine` does not support custom field `mmsegext` (see [url](https://github.com/open-mmlab/mmengine/blob/main/mmengine/config/utils.py#L16)), so I modified the value of the imported library variable (see [line 7 and 9](https://github.com/chenller/mmseg-extension/blob/main/mmsegext/__init__.py#L7)) to support the `mmsegext` field. So it is necessary to execute `import mmsegext` after `import mmengine.config` (see [url](https://github.com/chenller/mmseg-extension/blob/main/tools/train.py#L13)). 
**Using an absolute path to reference config can permanently avoid this issue.**
Solution 1: Use an absolute path. Change code `mmsegext::_base_/datasets/ade20k_512_tta_without_ratio.py` to `/absolute path/configs/_base_/datasets/ade20k_512_tta_without_ratio.py`.
Solution 2: Download the latest `mmsegext` code, I have fixed this error.
3. About the user manual of [mmengine.config](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html)

**Comment by bbbts** [comment]
> 1. Cancelling the comment is not necessary, I just want to let you know the environment I am using. You can do nothing about the file `requirements.txt`.
> 2. `mmengine` does not support custom field `mmsegext` (see [url](https://github.com/open-mmlab/mmengine/blob/main/mmengine/config/utils.py#L16)), so I modified the value of the imported library variable (see [line 7 and 9](https://github.com/chenller/mmseg-extension/blob/main/mmsegext/__init__.py#L7)) to support the `mmsegext` field. So it is necessary to execute `import mmsegext` after `import mmengine.config` (see [url](https://github.com/chenller/mmseg-extension/blob/main/tools/train.py#L13)).
>    **Using an absolute path to reference config can permanently avoid this issue.**
>    Solution 1: Use an absolute path. Change code `mmsegext::_base_/datasets/ade20k_512_tta_without_ratio.py` to `/absolute path/configs/_base_/datasets/ade20k_512_tta_without_ratio.py`.
>    Solution 2: Download the latest `mmsegext` code, I have fixed this error.
> 3. About the user manual of [mmengine.config](https://mmengine.readthedocs.io/en/latest/advanced_tutorials/config.html)

Thank you so much for the help. I did everything as instructed. However, I am getting this error now - 

The error is - "ModuleNotFoundError: No module named 'mmsegextlib_msda'" as seen below - 

<img width="749" alt="image" src="https://github.com/user-attachments/assets/3ca28296-07b1-420a-8d13-5365fa763bb4">

**Comment by chenller** [comment]
I think it's possible that the dependent library is not installed. Open install.sh, execute the commands in the file line by line in the terminal, and you will see the compilation process.

**Comment by bbbts** [comment]
> I think it's possible that the dependent library is not installed. Open install.sh, execute the commands in the file line by line in the terminal, and you will see the compilation process.

Thank you so much for the reply. 
I tried to execute the first command of the install.sh file "python setup.py build install" as seen below -
<img width="267" alt="image" src="https://github.com/user-attachments/assets/4b3d53ed-9735-4bc3-8e79-d380b842b1a9">

However, I am getting the following error "NotImplementedError: Cuda is not availabel"- 
<img width="773" alt="image" src="https://github.com/user-attachments/assets/8cb58715-e846-4bbe-a0a5-22001c415e80">

I tried to do the following to install cuda==10.0 as but getting error as shown below - 
<img width="510" alt="image" src="https://github.com/user-attachments/assets/785ce15d-867e-4c44-ac40-30e3c20a478f">

Thanks in advance!

**Comment by chenller** [comment]
If compilation is required, you should ensure that the CUDA version corresponds to the PyTorch version. There are two solutions: one is to install the pytorch version corresponding to the CUDA version, and the other is to install the CUDA version corresponding to the pytorch version.
![image](https://github.com/user-attachments/assets/eea7341f-ab94-4d02-8f17-356f11b3c82d)
My CUDA Environment:
![image](https://github.com/user-attachments/assets/4a99fe8c-c78c-47a8-8d64-40e4cbf09e91)
My Pytorch Environment:
![image](https://github.com/user-attachments/assets/6b63fa81-d001-4b3c-9d98-0ef0658714f8)

**Comment by bbbts** [comment]
> If compilation is required, you should ensure that the CUDA version corresponds to the PyTorch version. There are two solutions: one is to install the pytorch version corresponding to the CUDA version, and the other is to install the CUDA version corresponding to the pytorch version. ![image](https://private-user-images.githubusercontent.com/62296334/356846454-eea7341f-ab94-4d02-8f17-356f11b3c82d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODA3NDMsIm5iZiI6MTcyMzQ4MDQ0MywicGF0aCI6Ii82MjI5NjMzNC8zNTY4NDY0NTQtZWVhNzM0MWYtYWI5NC00ZDAyLThmMTctMzU2ZjExYjNjODJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE2MzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0NTlhYWRkOTFjODc1NTllY2Y4Y2ZlODU2ODY1MTcxMDg1NGIzNzc3NzkzNDliMmIxYTIyNmJhYWM5MzRkNDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CUWbWQZi6D2-PfT5dCz73RMR3HJSw-pLxfe8ahWLw8k) My CUDA Environment: ![image](https://private-user-images.githubusercontent.com/62296334/356846603-4a99fe8c-c78c-47a8-8d64-40e4cbf09e91.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODA3NDMsIm5iZiI6MTcyMzQ4MDQ0MywicGF0aCI6Ii82MjI5NjMzNC8zNTY4NDY2MDMtNGE5OWZlOGMtYzc4Yy00N2E4LThkNjQtNDBlNGNiZjA5ZTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE2MzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTc0OTdlZTQ2YmI2ZjUyZjdiMTRkMWNjMmZhNzRjNTVkNWViYWE2OGY3OWEwNzg4M2YyODI2ZGFhMWI4YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._n_DLohpvAzAanEM47oMQeGC6endgE_p4loNFf7DVpM) My Pytorch Environment: ![image](https://private-user-images.githubusercontent.com/62296334/356846639-6b63fa81-d001-4b3c-9d98-0ef0658714f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0ODA3NDMsIm5iZiI6MTcyMzQ4MDQ0MywicGF0aCI6Ii82MjI5NjMzNC8zNTY4NDY2MzktNmI2M2ZhODEtZDAwMS00YjNjLTlkOTgtMGVmMDY1ODcxNGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDE2MzQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiZjAzMTgzYmNlOGMyYTczZDU2NDIzZDI0OWViZDg0NWUyMmUzZDUyYzM2ZTNiNWU4ZjY5OWMwNTU4YzQ4MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CfKuiHou2C-C2lRnoc10OlpMKF5M9e5p9uFOZ9WuMWE)

Thank you so much for your help.
I am sorry for the question again.
I was actually trying to create an environment from scratch again. I followed the exact steps below to create it - 
<img width="673" alt="image" src="https://github.com/user-attachments/assets/1bb9b712-e7bd-4c4f-9b24-58b5b52a1e0e">

As you can see, in step 10, I was trying to execute the command "bash install.sh". However I am getting the following many errors - "The detected CUDA version (10.0) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions."
<img width="791" alt="image" src="https://github.com/user-attachments/assets/331c0d78-ea95-4fa8-9277-48afa360371e">

As per your instructions, I tried to install pytorch according to the cuda version that was detected (10.0) from [https://pytorch.org/get-started/previous-versions/](url)
but I am not able to find any version that matches 10.0. As you can see, the version 10.0 is not available (since my errors says - "The detected CUDA version (10.0) mismatches the version that was used to compile
PyTorch (12.1). Please make sure to use the same CUDA versions."). The lowest version available is 11. 8 - 
<img width="548" alt="image" src="https://github.com/user-attachments/assets/30e5a9ee-650c-445a-ba8b-4ffa4f3b9ec3">

Sorry for the bother. Kindly help.
Should I change my steps from step 1 itself? should I start form scratch?

**Comment by chenller** [comment]
You are about to succeed.

In this situation, you must upgrade your CUDA version. CUDA 10.2, CUDA 11.6, and CUDA 11.7 are good choices, and you can also choose higher versions. At the same time, it is necessary to install CUDNN that corresponds to the CUDA version. Then create an environment and install PyTorch.

The pytorch version is not very important, you should first ensure that pytorch corresponds to the CUDA version.

Please refer to the command for installing pytorch, corresponding to different versions of CUDA.

```shell

# CUDA 10.2
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=10.2 -c pytorch

# CUDA 11.6
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia

# CUDA 11.7
conda install pytorch==2.0.0 torchvision==0.15.0 torchaudio==2.0.0 pytorch-cuda=11.7 -c pytorch -c nvidia

```

**Comment by chenller** [comment]
You don't need to execute the 'pip install - r requirements. txt' command, just follow the steps in the documentation to install and use it
